### ISSUE TITLE
链接没有问题，但头像加载不出来

### ISSUE THREAD

**Issue by pcprinciple** [galnetwen/H-Siren#12]

**Comment by pcprinciple** [comment]
我检查了下首页html文件，头像代码是这样的：
<img src="https://cdn.v2ex.com/gravatar/91dad24d70af052d0b7f43b67c2ecad3?s=96&amp;d=mm&amp;r=g">

**Comment by pcprinciple** [comment]
`<img src="https://cdn.v2ex.com/gravatar/91dad24d70af052d0b7f43b67c2ecad3?s=96&amp;d=mm&amp;r=g">`

**Comment by pcprinciple** [comment]
推出管理员wordpress账号后，可以正确显示头像

**Comment by galnetwen** [comment]
你登录的账号必须在 Gravatar 上传过头像才会显示的，上传后需要等待 V2EX 同步，不会立马刷新。
未登录状态下显示本地设置头像，登录显示 Gravatar 头像。
